// Workspace copy: Simplified Chinese key, English, Japanese.
export const workspaceCopy: Record<string, readonly [string, string]> = {
'仅 Demo 演示，线上功能无需修改': ['Demo only; no changes to the live feature are needed.', 'デモ用です。公開中の機能は変更不要です。'],
'编辑蒙版': ["Edit mask", "マスクを編集"],
'示例服装': ["Sample garment", "サンプル衣服"],
'智能识别': ["Auto-detect", "自動認識"],
'智能识别中，请稍后...': ["Detecting, please wait...", "認識中です。しばらくお待ちください…"],
'效果准备中...': ["Preparing preview...", "プレビューを準備中…"],
'请先从左侧智能识别或涂抹蒙版区域': ["First detect or paint a mask in the left preview.", "左側で自動認識するか、マスク範囲を塗ってください。"],
'套索': ["Lasso", "投げ縄"],
'画笔': ["Brush", "ブラシ"],
'橡皮擦': ["Eraser", "消しゴム"],
'清除蒙版': ["Clear mask", "マスクをクリア"],
'上装': ["Top", "トップス"],
'印花缩放': ["Print scale", "柄の拡大縮小"],
'预览视图左侧编辑蒙版区域，右侧可缩放拼接的印花大小；': ["Edit the mask on the left and scale the repeating print on the right.", "左側でマスクを編集し、右側で繰り返し柄のサイズを調整できます。"],
'左侧编辑蒙版区域后，右侧展示的印花上身区域跟随改变。': ["Changes to the mask update the garment print area on the right.", "左側のマスク範囲を変更すると、右側のプリント範囲も変わります。"],
'印花图': ['Print image', '柄画像'],
'印花上身预览': ['Garment print preview', '着用プリントプレビュー'],
'上身效果预览说明': ['Preview guide', 'プレビューについて'],
'效果图仅作粗略参考，最终效果以AI生成后为准；': ['This preview is a rough reference. The final appearance depends on the AI-generated result.', 'プレビューは参考用です。最終的な仕上がりはAI生成結果をご確認ください。'],
'预览视图左侧可快速去除印花底色，右侧可拖拽调整印花位置、大小与角度；': ['Remove the print background on the left; drag on the right to adjust its position, size and angle.', '左側で柄の背景を削除し、右側で位置・サイズ・角度を調整できます。'],
'左侧印花去底后，右侧印花也会变为去底效果。': ['Removing the background on the left also updates the print on the right.', '左側で背景を削除すると、右側の柄にも反映されます。'],
'确认并生成': ['Confirm and generate', '確認して生成'],
'重置': ['Reset', 'リセット'],
'模特': ['Model', 'モデル'],
'模特图': ['Model image', 'モデル画像'],
'添加模特图': ['Add model image', 'モデル画像を追加'],
'模特库选择': ['Choose from models', 'モデルライブラリから選択'],
'最多添加1张印花图片': ['Add up to 1 print image', '柄画像は1枚まで追加できます'],
'最多添加1张模特图片': ['Add up to 1 model image', 'モデル画像は1枚まで追加できます'],
'印花方式': ['Print placement', 'プリント方式'],
'指定位置': ['Position', '位置を指定'],
'满印': ['All-over', '全面プリント'],
'调整印花位置': ['Adjust print position', 'プリント位置を調整'],
'服装建议为平铺图，若您的图片非平铺图，建议使用“转3D平铺”后再次使用': ['A flat-lay garment image is recommended. Otherwise, use “3D flat lay” first.', '服の平置き画像を推奨します。平置きでない場合は、先に「3D平置き」をご利用ください。'],
'模特库选择将在后续 Demo 中演示': ['Model library selection will be shown in a later demo.', 'モデルライブラリの選択は今後のデモで実演します。'],
'复制提示词': ['Copy prompt', 'プロンプトをコピー'],
'更多': ['More', 'その他'],
'下载该组结果图': ['Download all results', 'このタスクの結果をすべてダウンロード'],
'再次生成': ['Generate again', '再生成'],
'删除此条记录': ['Delete this record', 'この記録を削除'],
'删除确认': ['Confirm deletion', '削除の確認'],
'删除后不可恢复，是否确认删除？': ['This cannot be undone. Delete this record?', '削除すると元に戻せません。この記録を削除しますか？'],
'删除当前图片后不可恢复，是否确认删除？': ['This image cannot be restored. Delete it?', 'この画像を削除すると元に戻せません。削除しますか？'],
'暂无任务记录': ['No task records yet', 'タスク履歴はまだありません'],
'上传图片开始你的设计': ['Upload an image to start designing', '画像をアップロードしてデザインを始めましょう'],
'暂无结果图片': ['No result images', '結果画像はありません'],
'确认删除': ['Delete', '削除する'],
'收藏到资源库': ['Save to resource library', '素材ライブラリに保存'],
'提示词名称': ["Prompt name", "プロンプト名"],
'请输入名称': ["Enter a name", "名前を入力"],
'新增提示词': ["New prompt", "プロンプトを追加"],
'搜索提示词': ["Search prompts", "プロンプトを検索"],
'请输入关键词搜索': ["Search by keyword", "キーワードで検索"],
'编辑提示词名称': ["Edit prompt name", "プロンプト名を編集"],
'编辑提示词内容': ["Edit prompt content", "プロンプト内容を編集"],
'请输入提示词内容...': ["Enter prompt content...", "プロンプト内容を入力…"],
'提示词标题': ["Prompt title", "プロンプトのタイトル"],
'提示词内容': ["Prompt content", "プロンプト内容"],
'编辑提示词': ["Edit prompt", "プロンプトを編集"],
'提示词详情': ["Prompt details", "プロンプトの詳細"],
'提示词操作': ["Prompt actions", "プロンプトの操作"],
'没有匹配的提示词': ["No matching prompts", "一致するプロンプトがありません"],
'选择或新增一条提示词': ["Select or create a prompt", "プロンプトを選択または追加"],
'暂无数据': ["No data yet", "データがありません"],
'当前没有可展示的内容': ["There is no content to display yet", "表示できるコンテンツがありません"],
'另存为': ["Save as", "名前を付けて保存"],
'编辑': ["Edit", "編集"],
'保存': ["Save", "保存"],
'置顶': ["Pin", "ピン留め"],
'取消置顶': ["Unpin", "ピン留めを解除"],
'已置顶': ["Pinned", "ピン留めしました"],
'已取消置顶': ["Unpinned", "ピン留めを解除しました"],
'_副本': ["_copy", "_コピー"],
'封面图': ["Cover image", "カバー画像"],
'封面图（非必填）': ["Cover image (optional)", "カバー画像（任意）"],
'非必填': ["Optional", "任意"],
'上传封面图': ["Upload cover", "カバー画像をアップロード"],
'替换封面图': ["Replace cover", "カバー画像を変更"],
'移除封面图': ["Remove cover", "カバー画像を削除"],
'正在读取封面图': ["Loading cover image", "カバー画像を読み込み中"],
'封面图仅支持上传1张图片': ["Upload one cover image only", "カバー画像は1枚のみアップロードできます"],
'封面图上传失败，请使用20 MB以内的JPG、PNG、WebP或SVG图片': ["Could not upload the cover. Use a JPG, PNG, WebP or SVG image up to 20 MB.", "アップロードできませんでした。20 MB以下のJPG、PNG、WebPまたはSVG画像を使用してください。"],
 '浏览器站点储存配额不足，未保存的内容已保留': ["Site storage quota exceeded. Your unsaved changes are retained.", "サイトの保存容量を超えました。未保存の内容は保持されています。"],
'浏览器禁止此页面储存数据，请检查隐私设置': ["Browser storage is blocked. Check your privacy settings.", "保存がブロックされています。プライバシー設定をご確認ください。"],
'提示词储存失败，内容已保留，请重试': ["Could not save the prompt. Your changes are retained; please retry.", "保存できませんでした。内容は保持されています。もう一度お試しください。"],
'正在保存，请稍候': ["Saving, please wait", "保存中です。お待ちください"],
'保存失败，请检查浏览器存储空间': ["Save failed. Check your browser storage space.", "保存できませんでした。ブラウザーの空き容量をご確認ください。"],
'推荐色板': ['Suggested colors', 'おすすめの色'], '屏幕取色': ['Pick a screen color', '画面から色を取得'],
'饱和度与明度': ['Saturation and brightness', '彩度と明度'], '饱和度': ['Saturation', '彩度'], '明度': ['Brightness', '明度'], '色相': ['Hue', '色相'],
'当前浏览器不支持屏幕取色，请使用色板或输入颜色值': ['Screen color picking is unavailable in this browser. Use the palette or enter a color value.', 'このブラウザーでは画面から色を取得できません。色板またはカラーコードを使用してください。'],
'取色失败，请重试': ['Could not pick a color. Try again.', '色を取得できませんでした。再試行してください。'],
'收起左侧栏': ['Collapse left sidebar', '左サイドバーを閉じる'],
'暂无图层': ['No layers', 'レイヤーがありません'],
'图片缩略图': ['Image thumbnails', '画像サムネイル'],
'无需修改，Demo 不作展示': ['No changes required. Not shown in this demo.', '変更不要のため、Demoでは表示しません'],
'款式 - 款式裂变': ['Garment - Style variations', 'スタイル - バリエーション'],
'款式 - 局部修改有prompt示例': ['Garment - Prompt-based edit example', 'スタイル - プロンプト編集例'],
'服装图': ['Garment image', '服の画像'], '参考图': ['Reference image', '参考画像'],
'连衣裙': ['Dress', 'ワンピース'], '深V领': ['Deep V-neck', '深いVネック'],
'前中系带': ['Front tie', 'フロントリボン'], '短款长度': ['Short length', 'ショート丈'],
'飘逸垂坠': ['Flowing drape', '軽やかなドレープ'], '发散程度：中': ['Variation: Medium', 'バリエーション：中'],
'参考图2面料的颜色与质感，让图1的服装面料变成图2的质感与颜色，款式可以适当微调，比如领口可以更加V，袖口可以加长，保持灯笼袖，开口': ['Use the fabric color and texture from image 2 on the garment in image 1. Adjust the style slightly: deepen the V-neck, lengthen the cuffs, and keep the balloon sleeves and opening.', '画像2の生地の色と質感を画像1の服に適用。Vネックを深く、袖口を長くするなど微調整し、バルーンスリーブと開きは維持してください。'],
'帮我换两个颜色看看，紫色，小碎花': ['Show two variations: purple and a small floral print.', '紫色と小花柄の2パターンを見せてください。'],
'提示词库': ['Prompt library', 'プロンプトライブラリ'], '保存提示词': ['Save prompt', 'プロンプトを保存'],
'已保存': ['Saved', '保存済み'], '提示词已保存': ['Prompt saved', 'プロンプトを保存しました'],
'提示词已复制': ['Prompt copied', 'プロンプトをコピーしました'], '复制失败，请重试': ['Copy failed. Try again.', 'コピーに失敗しました。再試行してください。'],
'图片加载失败，请重试': ['Image failed to load. Try again.', '画像の読み込みに失敗しました。再試行してください。'],
'暂无保存的提示词': ['No saved prompts yet', '保存済みのプロンプトはありません'], '待生成': ['Pending generation', '生成待ち'],
'最多添加4张参考图片': ['Add up to 4 reference images', '参考画像は最大4枚まで追加できます'],
'选择清晰度': ['Image quality', '画質を選択'], '生成数量': ['Number of images', '生成枚数'],
'快速': ['Fast', '高速'], '高清': ['HD', '高画質'], '超清': ['Ultra HD', '超高画質'],
'支持 JPG、PNG、WebP、SVG，单张图片不超过 20 MB': ['Supports JPG, PNG, WebP and SVG, up to 20 MB per image', 'JPG・PNG・WebP・SVG対応、1枚あたり最大20 MB'],
'暂未接入此功能': ['This feature is not available yet', 'この機能はまだ利用できません'],
'描述你想如何修改这张图片': ['Describe how you want to edit this image', 'この画像をどのように編集したいか入力'],
'编辑图片': ['Edit image', '編集対象'], '参考图片': ['Reference image', '参考画像'],
'添加图片': ['Add image', '画像を追加'], '从画布中选择': ['Choose from canvas', 'キャンバスから選択'],
'生成设置': ['Generation settings', '生成設定'], '智能': ['Auto', '自動'], '{count}张': ['{count} image(s)', '{count}枚'],
'图片比例': ['Aspect ratio', 'アスペクト比'], '分辨率': ['Resolution', '解像度'], '图片数量': ['Image count', '画像数'],
'30 / 张': ['30 / image', '30 / 枚'],
'画布': ['Canvas', 'キャンバス'], '元素': ['Elements', '要素'], '抓手': ['Hand', 'ハンド'], '选择': ['Select', '選択'],
'穿透选择': ['Select behind', '背面の要素を選択'], '放大画布': ['Zoom in', 'キャンバスを拡大'], '缩小画布': ['Zoom out', 'キャンバスを縮小'],
'适合屏幕': ['Fit to screen', '画面に合わせる'], '实际大小': ['Actual size', '実際のサイズ'],
'复制为图片': ['Copy as image', '画像としてコピー'], '粘贴': ['Paste', '貼り付け'], '剪切': ['Cut', '切り取り'],
'全选': ['Select all', 'すべて選択'], '多选': ['Multi-select', '複数選択'], '取消': ['Cancel', 'キャンセル'],
'建组': ['Group', 'グループ化'], '解组': ['Ungroup', 'グループ解除'],
'资产': ['Assets', 'アセット'], '生成记录': ['Generation records', '生成記録'], '任务': ['Tasks', 'タスク'],
'新建对象': ['Create objects', 'オブジェクトを作成'], '层级操作': ['Layer operations', '重なり順の操作'],
'文本': ['Text', 'テキスト'], '椭圆': ['Ellipse', '楕円'], '线段': ['Line', '直線'],
'空格+拖动 / 按住中键拖动': ['Space + drag / Middle-button drag', 'Space＋ドラッグ / 中ボタンドラッグ'],
'V / 单击左键': ['V / Left-click', 'V / 左クリック'], 'Ctrl + 单击左键': ['Ctrl + Left-click', 'Ctrl＋左クリック'],
'Ctrl + + / 滚轮': ['Ctrl + + / Scroll wheel', 'Ctrl＋+ / ホイール'], 'Ctrl + − / 滚轮': ['Ctrl + − / Scroll wheel', 'Ctrl＋− / ホイール'],
'按住左键+拖动': ['Left-button drag', '左ボタンでドラッグ'],
'图片右键菜单': ['Image context menu', '画像のコンテキストメニュー'],
'下载格式': ['Download format', 'ダウンロード形式'], '图层顺序': ['Layer order', '重なり順'],
'复制并粘贴': ['Duplicate', '複製'], '复制': ['Copy', 'コピー'], '删除': ['Delete', '削除'],
'设为项目封面': ['Set as project cover', 'プロジェクトのカバーに設定'],
'已设为项目封面': ['Set as project cover', 'プロジェクトのカバーに設定しました'], '项目封面': ['Project cover', 'プロジェクトのカバー'],
'已复制，可在画布中粘贴': ['Copied. Paste on the canvas.', 'コピーしました。キャンバスに貼り付けできます。'],
'移到顶层': ['Bring to front', '最前面へ'], '上移一层': ['Bring forward', '前面へ'],
'下移一层': ['Send backward', '背面へ'], '移到底层': ['Send to back', '最背面へ'],
'当前浏览器不支持此格式导出，请选择其他格式': ['This browser cannot export this format. Choose another format.', 'このブラウザーはこの形式で書き出せません。別の形式を選択してください。'],
'当前画布共 {count} 个元素': ['{count} elements on the canvas', 'キャンバス内に{count}個の要素'],
'设计生产工作台 · {count} 张图片': ['Design workspace · {count} images', 'デザインワークスペース · {count}枚の画像'],
'设计生产工作台': ['Design workspace', 'デザインワークスペース'],
'无限画布。拖动空白处平移；按住 Control 或 Command 滚轮缩放；上传后可拖动图片。': ['Infinite canvas. Drag empty space to pan; Control or Command + scroll to zoom; drag images to move them.', '無限キャンバス。空白をドラッグして移動、Control または Command＋スクロールで拡大縮小、画像をドラッグして配置。'],
'收起右侧栏': ['Collapse sidebar', 'サイドバーを閉じる'], '展开右侧栏': ['Expand sidebar', 'サイドバーを開く'],
'开始设计': ['Start designing', 'デザインを始める'], 'Hello✨ 设计从这里开始': ['Hello✨ Your design starts here', 'Hello✨ ここからデザインを始めよう'],
'请先点击下方上传线稿图 / 款式图 / 图案 / 面料图': ['Upload a sketch, garment, pattern or fabric image below', '下から線画・スタイル・柄・生地の画像をアップロードしてください'],
'松开，将图片添加到画布': ['Drop to add images to the canvas', 'ドロップしてキャンバスに画像を追加'],
'项目概览': ['Project overview', 'プロジェクト概要'], '画布操作指南': ['Canvas guide', 'キャンバス操作ガイド'],
'联系客服': ['Contact support', 'お問い合わせ'], '积分账户': ['Credit balance', 'クレジット残高'],
'设计生产工作台 ·': ['Design workspace ·', 'デザインワークスペース ·'], '张图片': ['images', '枚の画像'],
'当前项目仅保留在本次打开的页面中。': ['This project is kept only for the current page session.', 'このプロジェクトは現在のページを開いている間のみ保持されます。'],
'返回画布': ['Back to canvas', 'キャンバスに戻る'],
'点击素材卡，或者将图片拖入画布，开始设计。': ['Click an asset card or drag images onto the canvas to start designing.', '素材カードをクリックするか、画像をキャンバスにドラッグしてデザインを始めましょう。'],
'平移画布': ['Pan canvas', 'キャンバスを移動'], '拖动空白处 / 空格 + 拖动 / 滚轮': ['Drag empty space / Space + drag / scroll', '空白をドラッグ / Space＋ドラッグ / スクロール'],
'适应屏幕': ['Fit to screen', '画面に合わせる'], '缩放画布': ['Zoom canvas', 'キャンバスを拡大・縮小'], 'Option / Alt + 滚轮': ['Option / Alt + scroll', 'Option / Alt＋スクロール'], '⌘ / Ctrl / Option / Alt + 滚轮，或触控板捏合': ['⌘ / Ctrl / Option / Alt + scroll, or pinch on a trackpad', '⌘ / Ctrl / Option / Alt＋スクロール、またはトラックパッドでピンチ'],
'移动图片': ['Move image', '画像を移動'], '按住图片拖动': ['Drag the image', '画像をドラッグ'],
'恢复 100% / 适应画布': ['Reset to 100% / Fit canvas', '100%に戻す / キャンバスに合わせる'],
'删除选中图片': ['Delete selected image', '選択した画像を削除'], '撤销上传、移动、删除': ['Undo upload, move or delete', 'アップロード・移動・削除を元に戻す'],
'当前 Demo 的图片仅保留在本次打开的页面中。': ['Demo images are kept only for the current page session.', 'デモの画像は現在のページを開いている間のみ保持されます。'],
'当前为设计生产工作台 Demo，暂未接入在线客服。': ['This workspace demo is not connected to live support.', 'このワークスペースのデモはオンラインサポートに未接続です。'],
'演示账户可用积分': ['Available demo credits', 'デモアカウントの利用可能クレジット'], '当前 Demo 暂未接入积分购买。': ['Credit purchases are not available in this demo.', 'このデモではクレジットを購入できません。'],
'请先选择图层': ['Please select a layer first', '先にレイヤーを選択してください'],
'图片': ['Image', '画像'], '替换图片': ['Replace image', '画像を置換'], '局部编辑': ['Edit area', '部分編集'], '转3D平铺': ['3D flat lay', '3D平置きに変換'], '图片编辑': ['Edit image', '画像編集'],
'基础参数': ['Basic properties', '基本設定'], '位置': ['Position', '位置'], '横坐标': ['X position', 'X座標'], '纵坐标': ['Y position', 'Y座標'],
'尺寸': ['Size', 'サイズ'], '宽度': ['Width', '幅'], '高度': ['Height', '高さ'], '变换': ['Transform', '変形'], '旋转角度': ['Rotation', '回転角度'],
'水平翻转': ['Flip horizontal', '左右反転'], '垂直翻转': ['Flip vertical', '上下反転'], '圆角': ['Corners', '角丸'], '圆角半径': ['Corner radius', '角丸の半径'],
'描边': ['Stroke', '線'], '颜色': ['Color', '色'], '描边颜色': ['Stroke color', '線の色'], '描边颜色代码': ['Stroke hex color', '線のカラーコード'],
'描边透明度': ['Stroke opacity', '線の不透明度'], '选择描边颜色': ['Choose stroke color', '線の色を選択'], '粗细': ['Weight', '太さ'], '描边粗细': ['Stroke weight', '線の太さ'],
'效果': ['Style', 'スタイル'], '实线': ['Solid', '実線'], '虚线': ['Dashed', '破線'], '点线': ['Dotted', '点線'],
'内描边': ['Inside stroke', '内側の線'], '居中描边': ['Centered stroke', '中央の線'], '外描边': ['Outside stroke', '外側の線'],
'外观': ['Appearance', '外観'], '不透明度': ['Opacity', '不透明度'], '输入文字': ['Enter text', 'テキストを入力'], '画框': ['Frame', 'フレーム'], '矩形': ['Rectangle', '長方形'],
'画布功能栏': ['Canvas features', 'キャンバス機能'], '图层': ['Layers', 'レイヤー'], '设计工具': ['Design tools', 'デザインツール'], '操作历史': ['History', '操作履歴'],
'多款融合': ['Merge styles', 'スタイル融合'], '面料套版': ['Apply fabric', '生地を適用'], '单款裂变': ['Style variations', 'スタイル展開'], '印花设计': ['Print design', 'プリントデザイン'], '工艺单素材包': ['Tech pack assets', '仕様書素材セット'],
'当前画布共': ['Canvas contains', 'キャンバス内：'], '个元素': ['elements', '個の要素'], '撤销上一步': ['Undo last action', '直前の操作を元に戻す'], '重做': ['Redo', 'やり直す'],
'画布工具栏': ['Canvas toolbar', 'キャンバスツールバー'], '选择 V': ['Select V', '選択 V'], '抓手 H': ['Hand H', 'ハンド H'], '撤销': ['Undo', '元に戻す'],
'添加矩形': ['Add rectangle', '長方形を追加'], '添加画框': ['Add frame', 'フレームを追加'], '添加文字': ['Add text', 'テキストを追加'], '上传图片': ['Upload images', '画像をアップロード'],
'缩小': ['Zoom out', '縮小'], '放大': ['Zoom in', '拡大'], '适应画布': ['Fit canvas', 'キャンバスに合わせる'], '整理画布': ['Arrange canvas', 'キャンバスを整理'],
'使用教程': ['Guide', '使い方'], '新手引导': ['Getting started', 'はじめてのガイド'], '快捷键': ['Keyboard shortcuts', 'ショートカット'], '旋转图片': ['Rotate image', '画像を回転'], '调整图片尺寸': ['Resize image', '画像のサイズを変更'],
'元素工具栏': ['Element toolbar', '要素ツールバー'], '快捷编辑': ['Quick edit', 'クイック編集'], '款式': ['Style', 'スタイル'], '印花': ['Print', 'プリント'], '面料': ['Fabric', '生地'], '线稿': ['Sketch', '線画'],
'更多操作': ['More actions', 'その他の操作'], '高清放大': ['Upscale', '高画質化'], '一键去底': ['Remove background', '背景を削除'], '智能抠图': ['Smart cutout', 'スマート切り抜き'],
'智能裁图': ['Smart crop', 'スマートトリミング'], 'AI扩图': ['AI expand', 'AI画像拡張'], 'AI消除': ['AI erase', 'AI消去'], '工艺单': ['Tech pack', '仕様書'],
'查看大图': ['View full image', '画像を拡大表示'], '取消收藏': ['Remove from favorites', 'お気に入りを解除'], '收藏': ['Favorite', 'お気に入り'], '下载原图': ['Download original', '元画像をダウンロード'],
'右侧面板': ['Sidebar', 'サイドパネル'], '图层属性': ['Layer properties', 'レイヤープロパティ'], 'AI助手': ['AI assistant', 'AIアシスタント'],
'新对话': ['New chat', '新しいチャット'], '新建对话': ['Start new chat', '新しいチャットを開始'], '暂无历史对话': ['No previous chats', 'チャット履歴はありません'],
'已记录设计需求。当前为交互 Demo，暂未接入 AI 生成。': ['Design request recorded. This interactive demo is not connected to AI generation.', 'デザイン要望を記録しました。この操作デモはAI生成に未接続です。'],
'今天你想设计什么？': ['What would you like to design today?', '今日は何をデザインしますか？'],
'从下方输入你的设计需求，或上传/从画布中选择图片进行修改与设计': ['Describe your design below, or upload / select an image from the canvas to edit.', '下にデザインの要望を入力するか、画像をアップロード／キャンバスから選択して編集してください。'],
'设计需求': ['Design request', 'デザインの要望'], '上传产品图，然后向我说出设计需求': ['Upload a product image and describe your design', '商品画像をアップロードして、デザインの要望を入力'],
'添加附件': ['Add attachment', '添付を追加'], '上传类型': ['Upload type', 'アップロードの種類'], '文件': ['File', 'ファイル'],
'选择要上传的文件': ['Choose files to upload', 'アップロードするファイルを選択'], '选择要上传的图片': ['Choose images to upload', 'アップロードする画像を選択'],
'发送设计需求': ['Send design request', 'デザインの要望を送信'], '文字内容': ['Text content', 'テキスト内容'], '添加到画布': ['Add to canvas', 'キャンバスに追加'],
'局部修改': ['Edit area', '部分修正'], '印花上身': ['Apply print', 'プリントを適用'], '面料替换': ['Replace fabric', '生地を置換'], '颜色修改': ['Change color', '色を変更'],
'AI试衣': ['AI try-on', 'AI試着'], '多视角': ['Multiple views', 'マルチアングル'], '款式裂变': ['Style variations', 'スタイル展開'], '风格迁移': ['Style transfer', 'スタイル転送'],
'四方连续': ['Seamless repeat', 'シームレスパターン'], '面料上身': ['Apply fabric', '生地を適用'], '面料创款': ['Design from fabric', '生地からデザイン'],
'线稿转实物': ['Sketch to product', '線画から実物へ'], '实物转线稿': ['Product to sketch', '実物から線画へ'], '转矢量图': ['Vectorize', 'ベクター化'],
'线稿转矢量': ['Vectorize sketch', '線画をベクター化'], '图案转矢量': ['Vectorize pattern', '柄をベクター化'],
'项目': ['Project', 'プロジェクト'], '返回项目': ['Back to project', 'プロジェクトに戻る'], '项目名称': ['Project name', 'プロジェクト名'], '重命名项目': ['Rename project', 'プロジェクト名を変更'],
'上传线稿图、款式图、图案或面料图': ['Upload a sketch, garment, pattern or fabric image', '線画・スタイル・柄・生地の画像をアップロード'],
'松开即可上传图片': ['Drop to upload images', 'ドロップして画像をアップロード'],
'点击、拖放上传图片，或者直接和AI聊一聊': ['Click or drop images, or chat with AI', 'クリック・ドロップで画像を追加、またはAIとチャット'],
'支持jpg、jpeg、png、webp、svg格式图片,最大支持20M以内图片': ['JPG, JPEG, PNG, WebP and SVG · Up to 20 MB per image', 'JPG・JPEG・PNG・WebP・SVG対応 · 1枚20 MBまで'],
'支持 JPG、PNG、WebP、SVG、GIF，单张图片不超过 20 MB': ['JPG, PNG, WebP, SVG and GIF supported. Maximum 20 MB per image.', 'JPG・PNG・WebP・SVG・GIF対応。1枚20 MBまで。'],
'部分图片无法读取，请重新选择': ['Some images could not be read. Please select them again.', '一部の画像を読み込めませんでした。もう一度選択してください。'],
'关闭': ['Close', '閉じる'], '移除': ['Remove', '削除'], '附件：': ['Attachment: ', '添付：'], '数值': ['value', '値'],
};
